Migrationsandentities
Kites-Foundation/hello-munnar-backend pull request #45
Opened 2021-01-29 22:43 UTC by tomahawk-pilot

2021-01-29 22:43 UTC, tomahawk-pilot commented
@Kites-Foundation/kites-hackathon-squad  please merge this before todays start of hack

2021-01-30 03:32 UTC, merged

2021-01-30 03:37 UTC, riginoommen requested changes

2021-01-30 03:37 UTC, riginoommen commented on src/activities/entities/activity.entity.ts
> +  imagesUrl: any;
Other places its imageUrl. And it's images url. CAN we make this change universal.

2021-01-30 03:38 UTC, riginoommen requested changes

2021-01-30 03:38 UTC, riginoommen commented on src/destinations/migrations/1611958664183-destination.ts
> +            name: 'Description',
```suggestion
            name: 'description',
```